### ISSUE TITLE
Hidden passwords use asterisks, which breaks special formatting on Slack.

### ISSUE THREAD

**Issue by clanzen** [ibm-cloud-solutions/hubot-environment#6]
The existing code hides passwords and other sensitive environment values with a list of 20 asterisks.  The output on slack will be a string of 10 asterisks with the middle 2 being highlighted.  This is caused by special handling in hubot-ibmcloud-formatter, and it needs to remain as is because the asterisk is a special character.  Using something else, like a list of pound signs (#) will be better.

**Comment by aeweidne** [comment]
Is it possible to escape the *?

**Comment by clanzen** [comment]
I gave it a shot and didn't have any luck.
